SELECT *
FROM MOVIE;

SELECT TITLE, YEAR
FROM MOVIE;

SELECT title, year, length, length/60
FROM MOVIE;

SELECT title, year, length, length/60 as hours
FROM MOVIE;

SELECT DISTINCT length/60 as HOURS
FROM MOVIE;


SELECT *
FROM MOVIE
WHERE length > 120;

SELECT TITLE, YEAR, STUDIONAME
FROM MOVIE
WHERE STUDIONAME = 'Fox';

SELECT NAME
FROM MOVIESTAR
WHERE BIRTHDATE = '1977-07-07';

SELECT TITLE, YEAR
FROM MOVIE
WHERE LENGTH IS NULL;

SELECT TITLE, YEAR
FROM MOVIE
WHERE LENGTH BETWEEN 100 AND 120;

SELECT TITLE, YEAR, LENGTH
FROM MOVIE
WHERE LENGTH IN (111, 124);

SELECT TITLE, YEAR
FROM MOVIE
WHERE TITLE LIKE 'St_r%';

SELECT TITLE, YEAR
FROM MOVIE
WHERE LENGTH NOT IN (111, 124)
AND TITLE LIKE 'S%'
OR TITLE LIKE '%Wars';

SELECT TITLE, YEAR
FROM MOVIE
WHERE LENGTH NOT IN (111, 124)
AND TITLE LIKE 'S%'
OR TITLE LIKE '%Wars';

SELECT STUDIONAME, TITLE, LENGTH
FROM MOVIE
WHERE LENGTH > 120
ORDER BY STUDIONAME DESC;