--task1
SELECT DISTINCT CONCAT(BATTLE , CONCAT('-', SHIP)) as BATTLE_SHIP, DATE
FROM OUTCOMES, BATTLES
WHERE BATTLE = NAME;

--task2
SELECT m.NAME, m.BIRTHDATE
FROM MOVIESTAR m
WHERE m.BIRTHDATE = (
    SELECT BIRTHDATE
    FROM MOVIESTAR
    WHERE MOD(YEAR(BIRTHDATE), 4) = 0 AND (MOD(YEAR(BIRTHDATE), 400) = 0 OR MOD(YEAR(BIRTHDATE), 100) <> 0)
    AND ABS(YEAR(BIRTHDATE) - YEAR(BIRTHDATE)) = 12
    );

--task3
SELECT '(' || TRIM(MS1.NAME) || ', ' || TRIM(MS2.NAME) || ')' AS PAIRS, MS1.BIRTHDATE AS MS1_DATE, MS2.BIRTHDATE AS MS2_DATE -- || IS CONCAT AND TRIM() TAKES OUT UNNEEDED WHITE SPACE
FROM MOVIESTAR MS1, MOVIESTAR MS2
WHERE MS1.BIRTHDATE > MS2.BIRTHDATE
AND   DAY(MS1.BIRTHDATE) = DAY(MS2.BIRTHDATE)
AND   MONTH(MS1.BIRTHDATE) = MONTH(MS2.BIRTHDATE);

--task4
SELECT R1.*
FROM
(SELECT S.NAME AS SNAME, S.LAUNCHED, B.NAME AS BNAME, B.DATE, YEAR(B.DATE) - S.LAUNCHED AS DIFF
FROM SHIPS S, OUTCOMES O, BATTLES B
WHERE S.NAME = O.SHIP AND O.BATTLE = B.NAME
AND YEAR(B.DATE) - S.LAUNCHED >= 0) R1
,
(SELECT O.SHIP, B.NAME, B.DATE
FROM OUTCOMES O, BATTLES B
WHERE O.BATTLE = B.NAME
AND B.DATE = ( SELECT MIN(DATE) FROM OUTCOMES, BATTLES WHERE BATTLE = NAME AND SHIP = O.SHIP))R2
WHERE R1.SNAME = R2.SHIP AND R1.BNAME = R2.NAME;

--task5
SELECT TITLE, YEAR, COALESCE(LENGTH, 0) AS LENGTH, COALESCE(STUDIONAME, 'Unknown') AS STUDIONAME
FROM MOVIE
WHERE COALESCE(LENGTH,0) = (SELECT MIN(COALESCE(LENGTH,0)) FROM MOVIE);

