--task1
SELECT DISTINCT m.COUNTRY
FROM CLASSES m
WHERE m.NUMGUNS >= ALL(
    SELECT NUMGUNS
    FROM CLASSES
    WHERE m.COUNTRY <> COUNTRY
    );

--task2
SELECT DISTINCT CLASS
FROM SHIPS
WHERE NAME IN(
    SELECT SHIP
    FROM OUTCOMES
    WHERE RESULT = 'sunk'
    );

--task3
SELECT DISTINCT NAME
FROM SHIPS
WHERE CLASS IN (
    SELECT CLASS
    FROM CLASSES
    WHERE BORE = 16
    );

--task4
SELECT BATTLE
FROM OUTCOMES
WHERE SHIP IN (
    SELECT NAME
    FROM SHIPS
    WHERE CLASS = 'Kongo'
    );

--task5
SELECT NAME
FROM SHIPS s, CLASSES m
WHERE NUMGUNS >= ALL (
    SELECT NUMGUNS
    FROM CLASSES
    WHERE BORE = m.BORE
    AND s.CLASS = m.CLASS
    )